CLASS /eacm/bp_i_upl_dodp DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF /eacm/i_upl_dodp .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /EACM/BP_I_UPL_DODP IMPLEMENTATION.
ENDCLASS.
